-- I Can Read Cinere attendance application users
-- Run this script in Supabase SQL Editor.
-- The backend reads this table only with SUPABASE_ROLE_KEY.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  user_id text primary key,
  password_hash text not null,
  title text not null default 'Team Member',
  phone text,
  role text not null default 'employee'
    check (role in ('employee', 'manager', 'admin')),
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_user_id_not_blank check (length(trim(user_id)) > 0)
);

create index if not exists app_users_active_role_idx
  on public.app_users (is_active, role);

create or replace function public.touch_app_users_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_users_touch_updated_at on public.app_users;
create trigger app_users_touch_updated_at
before update on public.app_users
for each row execute function public.touch_app_users_updated_at();

-- Add a user or replace their password and metadata.
-- Passwords are stored only as bcrypt hashes generated by pgcrypto.
create or replace function public.upsert_app_user(
  p_user_id text,
  p_password text,
  p_title text default 'Team Member',
  p_phone text default null,
  p_role text default 'employee',
  p_is_active boolean default true
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if length(trim(coalesce(p_user_id, ''))) = 0 then
    raise exception 'user_id is required';
  end if;

  if length(coalesce(p_password, '')) < 8 then
    raise exception 'password must contain at least 8 characters';
  end if;

  if p_role not in ('employee', 'manager', 'admin') then
    raise exception 'role must be employee, manager, or admin';
  end if;

  insert into public.app_users (
    user_id,
    password_hash,
    title,
    phone,
    role,
    is_active
  ) values (
    trim(p_user_id),
    crypt(p_password, gen_salt('bf', 12)),
    coalesce(nullif(trim(p_title), ''), 'Team Member'),
    nullif(trim(coalesce(p_phone, '')), ''),
    p_role,
    p_is_active
  )
  on conflict (user_id) do update set
    password_hash = excluded.password_hash,
    title = excluded.title,
    phone = excluded.phone,
    role = excluded.role,
    is_active = excluded.is_active,
    updated_at = now();
end;
$$;

-- Change only the password of an existing user.
create or replace function public.set_app_user_password(
  p_user_id text,
  p_new_password text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if length(coalesce(p_new_password, '')) < 8 then
    raise exception 'password must contain at least 8 characters';
  end if;

  update public.app_users
  set password_hash = crypt(p_new_password, gen_salt('bf', 12)),
      updated_at = now()
  where user_id = trim(p_user_id);

  if not found then
    raise exception 'user % was not found', p_user_id;
  end if;
end;
$$;

-- Disable direct browser access. The service role used by the Flask backend
-- bypasses RLS and remains able to read and update this table.
alter table public.app_users enable row level security;
revoke all on table public.app_users from anon, authenticated;
grant select, insert, update, delete on table public.app_users to service_role;

revoke all on function public.upsert_app_user(text, text, text, text, text, boolean) from public, anon, authenticated;
revoke all on function public.set_app_user_password(text, text) from public, anon, authenticated;
grant execute on function public.upsert_app_user(text, text, text, text, text, boolean) to service_role;
grant execute on function public.set_app_user_password(text, text) to service_role;

-- -------------------------------------------------------------------------
-- EXAMPLES — copy, uncomment, and replace every password before executing.
-- Keep user_id spelling/capitalisation identical to existing attendance data.
-- -------------------------------------------------------------------------

-- Employee:
-- select public.upsert_app_user(
--   'Muhidin',
--   'REPLACE_WITH_A_STRONG_PASSWORD',
--   'Mr',
--   '628xxxxxxxxxx',
--   'employee',
--   true
-- );

-- Manager:
-- select public.upsert_app_user(
--   'Hanny',
--   'REPLACE_WITH_A_STRONG_PASSWORD',
--   'Manager',
--   '628xxxxxxxxxx',
--   'manager',
--   true
-- );

-- Admin:
-- select public.upsert_app_user(
--   'Mita',
--   'REPLACE_WITH_A_STRONG_PASSWORD',
--   'Administrator',
--   '628xxxxxxxxxx',
--   'admin',
--   true
-- );

-- Change a password later:
-- select public.set_app_user_password(
--   'Muhidin',
--   'REPLACE_WITH_THE_NEW_PASSWORD'
-- );

-- Review users without exposing password hashes:
-- select user_id, title, phone, role, is_active, last_login_at, created_at, updated_at
-- from public.app_users
-- order by user_id;
